name: serve
base: core18
version: '0.1'
summary: incredibly simple and fast static file server
description: |
  This is a static file server written using Google's golang. It was
  primarily built to share files between computers on the same network
  but the use cases can be expanded beyond that, Forexample it can be
  installed in docker container to expose certain directory files.

grade: devel
confinement: devmode

parts:
  server:
    plugin: go
    go-importpath: github.com/piusalfred/serve
    source: .
    source-type: git

